name: Build docker container on publish
on:
  release:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'latest'
        type: string
jobs:
  var:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      image-llamacpp: "ghcr.io/mutablelogic/llamacpp"
      image-cuda-dev: "ghcr.io/mutablelogic/cuda-dev"
      image-cuda-runtime: "ghcr.io/mutablelogic/cuda-rt"
      tag: ${{ steps.var.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set variables
        id: var
        run: |
          if [ "${{ github.event_name }}" != "release" ] && [ "${{ inputs.tag }}" != "latest" ]; then
            TAG="${{ inputs.tag }}" && echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
          else
            TAG="$(git describe --tags)" && echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
          fi
  build:
    name: Build
    needs: var
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || matrix.arch == 'arm64' && 'nx1' }}
    env:
      ARCH: ${{ matrix.arch }}
      OS: linux
      DOCKER_REGISTRY: ghcr.io/mutablelogic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: build      
        run: |
          git checkout v${{ needs.var.outputs.tag }}
          make docker && make docker-push
  manifest:
    name: Create manifest
    needs: 
      - build
      - var
    runs-on: ubuntu-latest
    steps:
      - name: cuda-dev
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ needs.var.outputs.image-cuda-dev }}@${{ needs.var.outputs.tag }}
          sources: |
            ${{ needs.var.outputs.image-cuda-dev }}-linux-amd64@${{ needs.var.outputs.tag }}
            ${{ needs.var.outputs.image-cuda-dev }}-linux-arm64@${{ needs.var.outputs.tag }}
      - name: cuda-rt
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ needs.var.outputs.image-cuda-runtime }}@${{ needs.var.outputs.tag }}
          sources: |
            ${{ needs.var.outputs.image-cuda-runtime }}-linux-amd64@${{ needs.var.outputs.tag }}
            ${{ needs.var.outputs.image-cuda-runtime }}-linux-arm64@${{ needs.var.outputs.tag }}
      - name: llamacpp
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ needs.var.outputs.image-llamacpp }}@${{ needs.var.outputs.tag }}
          sources: |
            ${{ needs.var.outputs.image-llamacpp }}-linux-amd64@${{ needs.var.outputs.tag }}
            ${{ needs.var.outputs.image-llamacpp }}-linux-arm64@${{ needs.var.outputs.tag }}                        